// <auto-generated />
using CarParkSample.Models.ORM.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CarParkSample.Migrations
{
    [DbContext(typeof(CarParkContext))]
    [Migration("20210123190015_overridetypefixed")]
    partial class overridetypefixed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CarParkSample.Models.ORM.Lokasyon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Lokasyon_Adi")
                        .HasColumnType("text");

                    b.Property<string>("Lokasyon_Kodu")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Lokasyons");
                });

            modelBuilder.Entity("CarParkSample.Models.ORM.Park", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Calisma_Saatleri")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Park_Adi")
                        .HasColumnType("text");

                    b.Property<string>("Park_Kapasitesi")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Parks");
                });

            modelBuilder.Entity("CarParkSample.Models.ORM.ParkTipi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Park_Kapasitesi")
                        .HasColumnType("text");

                    b.Property<string>("Park_Tipi")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("ParkTipis");
                });

            modelBuilder.Entity("CarParkSample.Models.ORM.Record", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<double>("Aylik_Abonelik_Ucreti")
                        .HasColumnType("double precision");

                    b.Property<string>("Enlem_Boylam")
                        .HasColumnType("text");

                    b.Property<int>("ParkID")
                        .HasColumnType("integer");

                    b.Property<int>("Park_Et_Devam_Et_Noktasi")
                        .HasColumnType("integer");

                    b.Property<string>("Tarifesi")
                        .HasColumnType("text");

                    b.Property<int>("Ucretsiz_Parklanma_Suresi_dakika")
                        .HasColumnType("integer");

                    b.HasKey("_id");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("CarParkSample.Models.ORM._AltBolge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Alt_Bolge")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.ToTable("AltBolges");
                });

            modelBuilder.Entity("CarParkSample.Models.ORM._Bölge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Bolge")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.ToTable("Bölges");
                });

            modelBuilder.Entity("CarParkSample.Models.ORM._Ilce", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Ilce")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.ToTable("ilces");
                });
#pragma warning restore 612, 618
        }
    }
}
